### ISSUE TITLE
Plus de personnalisation 

### ISSUE THREAD

**Issue by ArtwoXYZ** [onestlatech/widget-engreve#7]
J'ai intégré le widget sur mon site e-commerce indé et des choses me manquent un peu.

J'aimerais notamment pouvoir avoir la **transparence du background** mais sans laisser la possibilité de fermer le widget lors des jours de mobilisations : je pense que ça montre quand même un peu qui se cache derrière ce widget et c'est intéressant.

Je pense que ça serait pas mal aussi de permettre de **mettre un autre bouton** ou un lien supplémentaire qui permettrais d'expliquer pourquoi on est en grève exactement (en quoi Cette marque particulière, Ces travailleurs sont touchés, etc.).

Un choix sur **les couleurs** ça pourrait aussi être pas mal même si c'est pas obligatoire.

J'imagine ensuite qu'il y aurait pas mal d'options supplémentaires qui pourrait être intéressantes (les [discutions au niveau des statistiques par exemple](https://github.com/onestlatech/widget-engreve/issues/5), laissez la possibilité d'être ajouté ou non à ces stats).

J'aimerais d'abord savoir ce que vous en pensez et pourquoi me pencher dessus.

**Comment by noelmace** [comment]
Tous ces cas nécessitent en effet de forker le projet pour l'instant. On pourrait déjà envisager d'offrir une documentation pour ça. Pour le reste, je pense qu'il serait préférable de minimiser le nombre d'options, afin de conserver une bonne maintenabilité et lisibilité (voir ci-dessous pourquoi exactement).

Vu la diversité de sujets, on sera sans doute amenés à diviser cette issue pour pouvoir effectuer des votes, mais autant la garder ici pour démarrer.
 
## style custom (couleur et transparence)

Etant donné que ce widget vise une compatibilité max, les initiateurs du projets ont fait le choix d'une iframe plutôt que d'un custom element (qui casserais la compatibilité IE), ce qui rend la customisation compliquée en effet. Tout se fait via des get parameters passés à la src de l'iframe, donc il faut prévoir tous les cas particuliers.
Pour le background : https://github.com/onestlatech/widget-engreve/blob/v2.0.1/src/index.js#L37

Perso, si c'est en effet nécessaire, je préférerais repenser cette approche plutôt que de multiplier les cas particuliers.

## contenu par défaut

Il peut en effet être interessant de discuter ensemble du wording et des liens à afficher "par défaut".
Ici, j'ai tâché d'être le plus léger possible pour permettre un affichage correct sur mobile. Le mieux à mon avis serait de garder un seul bouton, mais de faire pointer le lien sur une page spécifique de onestla.tech par défaut (suite à notre appel à blocage).

On pourrait également permettre de customiser l'url via une option pour les autres cas (cf. https://github.com/onestlatech/widget-engreve/blob/v2.0.1/src/index.js#L5-L13).

**Comment by noelmace** [comment]
Plus de customisation devant plutôt nous amener à remplacer ce projet par un autre plus moderne (de préférence via un Web Component), sujet pour lequel nous manquons de contributeurs, ce ferme cette issue, la considérant "hors-scope".

Une nouvelle issue afin de discuter d'un éventuel projet de remplacement porté par d'autres contributeurs sera la bienvenue.
