### ISSUE TITLE
Ouvrir dans un nouvel onglet

### ISSUE THREAD

**Issue by cchaudier** [onestlatech/widget-engreve#8]
Bonjour,

J'ai intégré le bandeau sur [le site de notre collectif d'indépendants](https://lydra.fr/) et sur [le site de ma communauté des Compagnons du DevOps](https://forum.compagnons-devops.fr/).

J'ai remarqué que sur la version bandeau de pied de page, le bouton "J'en suis. ->" ouvre le site reforme-retraite.info sur le même onglet.
Est-il possible d'avoir une variable qui permet d'avoir un comportement alternatif qui ouvre le site dans un nouvel onglet pour ne pas sortir le visiteur de nos site ?

D'autre part je trouve dommage de ne pas l’emmener sur le site https://onestla.tech

A bientôt et courage à tous ✊

**Comment by noelmace** [comment]
Oui en effet c'était un oubli de ma part. Je corrige l'adresse de destination de ce pas.
Concernant un paramètre pour cela, le sujet est discuté dans #7 .
